### ISSUE TITLE
Image download timeout too low

### ISSUE THREAD

**Issue by Borningstar** [floydpink/CachedImage#13]
https://github.com/floydpink/CachedImage/blob/51cac51597cf155412862cff244a6a2846b0b9f8/source/FileCache.cs#L77

When using the dedicated file cache it times out too quickly and so never loads the image. Should probably be 3000 milliseconds instead of 30.

**Comment by floydpink** [comment]
Good catch, @Borningstar - by the look of it, I think that property may have been assumed to be in seconds, when it was originally added.

Can you please send a PR to bump this to 5 or 10 seconds?
