### ISSUE TITLE
WinINet not caching images, probably because .net core 3.1

### ISSUE THREAD

**Issue by Borningstar** [floydpink/CachedImage#14]
I've got a .Net Core 3.1 WPF project, the bitmap caching stuff doesn't seem to work, I suspect it's an issue with the .Net Core implementation. I havent investigated further to confirm, but if anyone else runs into it the dedicated caching mode should work.

**Comment by DDR12** [comment]
It should work but it doesn't.
Line #83 that reads
`var response = await request.GetResponseAsync();`

Throws a System. Exception with a message: "Specified argument was out of the range of valid values. (Parameter 'value')
