### ISSUE TITLE
In WinRT Image is a sealed class

### ISSUE THREAD

**Issue by dumbledad** [floydpink/CachedImage#6]
The WinRT implementation of [Image](https://msdn.microsoft.com/en-us/library/windows/apps/xaml/BR242752(v=win.10).aspx?appId=Dev14IDEF1&l=EN-US&k=k(Windows.UI.Xaml.Controls.Image)%3bk(SolutionItemsProject)%3bk(TargetFrameworkMoniker-WindowsPhoneApp,Version%3dv8.1)%3bk(DevLang-csharp)&rd=true) is a sealed class so the initial subclassing will not work in that setting.

**Comment by floydpink** [comment]
As mentioned in the description of the project, this is a WPF control and is not supposed to be used with WinRT
